---
format: gfm
bibliography: references.bib
nocite: '@*'
---

# commonMZ
This is a collection of common *m/z* values found in mass spectrometry.
The tables are available through an R package.
You can find the table files in the "inst\extdata" subfolder.

Contributions are welcomed.

It contains these tab delimited files:

* **`contaminants_+.tsv`**: A table of common contaminant masses in positive ionization mode.
* **`contaminants_-.tsv`**: A table of common contaminant masses in negative ionization mode.
* **`adducts_fragments.tsv`**: A table of common fragment and adducts. The listed mass refers to mass differences.
* **`repeating_units_+.tsv`**: A table of common series of repeated units (mass differences) in positive ionization mode.
* **`repeating_units_-.tsv`**: A table of common series of repeated units (mass differences) in negative ionization mode.

And these excel files:

* **`CAMERA_rules_pos.xlsx`**: A table of common fragment and adducts for use with CAMERA in positive mode. The listed mass refers to mass differences to the uncharged species.
* **`CAMERA_rules_neg.xlsx`**: A table of common fragment and adducts for use with CAMERA in negative mode. The listed mass refers to mass differences to the uncharged species.
* **`CAMERA_rules_EI.xlsx`**: A table of common fragment and adducts for use with CAMERA in EI mode. The listed mass refers to mass differences to the uncharged species.

*Excel files are used to make it easier to work with since adducts/fragment types have been color coded*.



## Glossary

| Type of ions:           | Explanation                                                           |
|-------------------------|-----------------------------------------------------------------------|
| f+                      | fragment ion                                                          |
| [f+H]+                  | protonated fragment ion, e.g. in-source fragmentation of peptide ions |
| [M+H]+                  | protonated molecular ion (pseudomolecular ion)                        |
| [M+Na]+                 | sodiated molecular ion                                                |
| [M+K]+                  | potassiated molecular ion                                             |
| [M2+H]+, [M3+H]+ etc... | protonated dimeric, trimeric, etc... molecular ion                    |
| [AnBm+H]+               | protonated molecular ion consisting of n A and m B subunits           |


| Abbreviations | Explanation                                                                   |
|---------------|-------------------------------------------------------------------------------|
| 4-HCCA        | α-cyano-4-hydroxycinnamic acid, common matrix substance for MALDI MS analysis |
| 2,5-DHB       | 2,5-Dihydroxy benzoic acid, common matrix substance for MALDI MS analysis     |
| MeCN, ACN     | acetonitrile, solvent                                                         |
| MeOH          | methanol, solvent                                                             |
| MeNO2         | nitromethane, solvent                                                         |
| HABA          | 2-(4-hydroxyphenyl-azo)-benzoic acid, matrix substance for MALDI MS analysis  |
| SA            | sinapic or sinapinic acid, common matrix substance for MALDI MS analysis      |
| PEG           | Polyethylene glycol, Repeat unit: -[O-CH2-CH2-]-; 44 Da                       |
| PPG           | Polypropylene glycol, Repeat unit: -[O-C(CH3)H-CH2-]-; 58 Da                  |
| XaaCcamXaa    | carbamidomethylated cysteine residue (+ICH2CONH2 - HI), +57Da                 |
| XaaMoxXaa     | singly oxidized methionine residue (+O, 16 Da)                                |



## References
The data in these tables are primarily from:

* the Supplementary Data from: Keller BO, Sui J, Young AB, Whittal RM. Interferences and contaminants encountered in modern mass spectrometry. Anal Chim Acta. 2008;627(1):71-81.


In the tables each entry references refers to the following table:

| Label | First author(s) | Year |
|-------|-----------------|------|
| A  | Waters Corporation        | —    |
| B  | Applied Biosystems        | —    |
| C  | New Objective             | —    |
| D  | Sigma-Aldrich             | —    |
| E  | Thermo Corporation, Mahn  | —    |
| F  | Tong et al.               | 1999 |
| G  | Andersen et al.           | 1999 |
| H  | Keller & Li               | 2000 |
| I  | Keller et al.             | —    |
| J  | Harris et al.             | 2002 |
| K  | Keller et al.             | —    |
| L  | Schlosser & Volkmer-Engert | 2003 |
| M  | Tran & Doucette           | 2006 |
| N  | Verge & Agnes             | 2002 |
| O  | Paez & Howe               | 2004 |
| P  | Purves et al.             | 1997 |
| Q  | Gibson & Brown            | 2003 |
| R  | Beavis & Chait            | 1990 |
| S  | Guzzetta                  | —    |
| T  | Clauser et al.            | 1995 |
| U  | Macha et al.              | 2001 |
| V  | Pleasance et al.          | 1991 |
| W  | Xia et al.                | 2005 |
| X  | Guo et al.                | 2006 |
| Y  | Ijames et al.             | 1995 |
| Z  | Hesse et al.              | 1987 |
| AA | Stanstrup                 | —    |

Full bibliographic details:

::: {#refs}
:::
